"""changed notifications name and added notify_before

Revision ID: 789bfa168dc4
Revises: 6ac1841fecfd
Create Date: 2025-04-15 18:31:44.479871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789bfa168dc4'
down_revision = '6ac1841fecfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_before', sa.Integer(), nullable=True))
        batch_op.drop_column('notification_preferences')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_preferences', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('notify_before')
        batch_op.drop_column('notification_enabled')

    # ### end Alembic commands ###
